export const INVITE = '/invites';
export const MY_INVITE = '/invites/my';
export const INVITE_BY_ID = (id: number) => `/invites/${id}`;
export const MY_CLOCKS = '/clocks/my';
export const CLOCKS = '/clocks';
export const CLOCKS_SEARCH = '/clocks/search';
export const CLOCK_BY_ID = (id: number) => `/clocks/${id}`;
export const CLOCK_BY_PUBLIC_ID = (publicId: string) => `/clocks/public/${publicId}`;
export const CLOCK_BY_ID_READINGS = (clockId: number) => `/readings/${clockId}/`;
export const CLOCK_BY_PUBLIC_ID_READINGS = (publicId: string) => `/readings/public/${publicId}`;
export const CLOCK_BY_ID_INVOICES = (clockId: number) => `/invoices/${clockId}`;
export const CLOCK_BY_PUBLIC_ID_INVOICES = (publicId: string) => `/invoices/public/${publicId}`;
export const CLOCK_BY_ID_LAST_READING = (clockId: number) => `/readings/${clockId}/last`;
export const REVERT_LAST_READING = (clockId: number) => `/readings/${clockId}/revert-last-reading`;
